/*
 *	@(#) space.h 7.1 94/11/27 SCOINC
 *
 *      Copyright (C) The Santa Cruz Operation, 1994.
 *      This Module contains Proprietary Information of
 *      The Santa Cruz Operation and should be treated
 *      as Confidential.
 */

/* interrupt number */
#define R8E_0_IRQ	0x0
#define R8E_1_IRQ	0x0
#define R8E_2_IRQ	0x0
#define R8E_3_IRQ	0x0

/* Base I/O address */
#define R8E_0_BASE_IO	0x0
#define R8E_1_BASE_IO	0x0
#define R8E_2_BASE_IO	0x0
#define R8E_3_BASE_IO	0x0

/* line speed 100bps =100,10bps =10, auto =0;  */
#define R8E_0_FORCE	0x0
#define R8E_1_FORCE	0x0
#define R8E_2_FORCE	0x0
#define R8E_3_FORCE	0x0
